FROM python:3.11

WORKDIR /app

# Копируем файлы тестов
COPY test_service.py .
COPY demo_test_cases.json .
COPY requirements.txt .

# Устанавливаем зависимости для тестов
RUN pip install -r requirements.txt

# Запускаем тесты
CMD ["python", "test_service.py"]